### ISSUE TITLE
NIMAS will not successfully convert using dtbook scripts for HTML, RTF, PEF or ODT

### ISSUE THREAD

**Issue by nicolegaines** [daisy/pipeline#639] opened 2022-05-19 13:37 UTC
### Expected Behavior
dtbook conversion scripts in Pipeline 2 should work with NIMAS files, as these XML files validate to Z39.86. 

### Actual Behavior

Using command line, I tried multiple tests to convert NIMAS to odt, html, rtf and pef. 
1. ODT test generated a file but Word could not open the file. Command line output and the Word error were sent to the daisy email address. It indicated that much of the file could not be rendered. Once the file was "recovered" it could not be opened. 
2. The HTML test produced no output. Command line output was sent to daisy email address.
3. The RTF test generated an RTF file but with no images. Command line output was sent to daisy email address.
4. The PEF test produced no output. Command line output was sent to daisy email address.

### Environment

Windows 10 64-bit
Client version:                 2.1.5
Pipeline version:               1.14.4
Pipeline authentication:        false

### Logs

[daisy-pipeline-webservice.1.log.zip](https://github.com/daisy/pipeline/files/8729546/daisy-pipeline-webservice.1.log.zip)
[daisy-pipeline-webservice.log](https://github.com/daisy/pipeline/files/8729547/daisy-pipeline-webservice.log)

**Comment by bertfrees** [comment] 2022-05-19 19:11
Thanks for the report. To which email address did you sent the files? I did not receive anything. Could you also send us the NIMAS files that you used for your tests please?

**Comment by nicolegaines** [comment] 2022-06-16 20:06
Hi, Bert. I received permission from McGraw-Hill to provide you the complete NIMAS file set. If I upload to this site, will the file be secure or is it open to anyone with a GitHub account? Might be better for me to provide the file in some other way. Just give me a ping. Thanks!
Nicole

**Comment by bertfrees** [comment] 2022-06-23 11:40
Hi @nicolegaines. You say

> these XML files validate to Z39.86

but when I validate the XML with the DTBook Validator script, I'm getting the following validation issues:

- character content of element "pagenum" invalid; must be an integer (43 times)
- There must be exactly one dtb:uid metadata item
- There must be at least one dc:Title metadata item

This is the reason why at least the DTBook to HTML conversion fails. I haven't looked into the other conversions yet.

Note that the DTBook to HTML script does have a "assert-valid" option which could in theory be used to ignore these validation issues, but in practice that doesn't really work at the moment.

**Comment by nicolegaines** [comment] 2022-06-23 12:08
Hi, Bert. Thanks for looking into this. Because NIMAS is a subset of DAISY, not all elements required for DAISY are present in NIMAS. (As an aside, I worked with Romain Deltour many years ago as he was working on a validator in the tool for NIMAS, but I believe the script as it exists now in Pipeline 2 still includes output relevant only to full DAISY files and not applicable to NIMAS source files. The NIMAC itself uses a validation tool custom built for NIMAS validation by OverDrive.)

I think the second two issues below are related to metadata included in the <head> tag of the XML in DAISY; however, metadata for NIMAS is only provided in the OPF, not in the XML file. NIMAS calls for the <head> tag of the XML to remain empty.

The <dc:Title> tag is used in the NIMAS OPF, but dtb:uid is not. NIMAS uses the <dc:Identifier> tag for the unique identifier for the file set. For example:

<dc:Identifier id="NIMAS9780545854665" scheme="NIMAS">9780545854665NIMAS</dc:Identifier>

With regard to the <pagenum> output, I think this may be an error in the validator. The DAISY Structure Guidelines have a provision for non-integer page number content (which is fairly common in U.S. textbooks). This content is indicated using the page attribute "special" on the pagenum tag. For example:


<pagenum id="pt3-ch4-app1-1" page="special">W-1</pagenum>

(Details found at http://www.daisy.org/z3986/structure/SG-DAISY3/part2-inline.html#pagenum)

Just let me know if I can help with any other information. Thanks again for looking into this!

Nicole




________________________________

**Comment by bertfrees** [comment] 2022-06-27 12:59
I can not reproduce the error in the DTBook to PEF conversion. It may be a bug that was fixed in the meantime.

**Comment by bertfrees** [comment] 2022-06-27 16:41
Regarding the DTBook to ODT conversion:

The "Some content cannot be rendered here" warnings have nothing to do with using a NIMAS as input, I think. These are just shortcomings of the script.

The .odt file that you emailed can be opened just fine in LibreOffice. It could however be that the document has some issues that LibreOffice can cope with, but MS Word not. I ran the file through a ODF validator and it identified some issues. It could in theory also be that Word does not fully/correctly support ODF. Note that the script was primarily tested with OpenOffice/LibreOffice, much less with MS Word.

**Comment by nicolegaines** [comment] 2022-10-11 07:00
Hi, Bert. I sent the emails to ***@***.***, which is the address Avneesh had provided. I just forwarded four emails to your email address. Thanks so much for looking into this for us!

Nicole
________________________________

**Comment by nicolegaines** [comment] 2022-10-11 07:54
Thanks, Bert. Your understanding is what I had also always assumed in terms of the Pipeline not supporting NIMAS conversion--not all elements required for full DAISY are present in NIMAS and so it makes sense to me that additional work would be required to make the scripts work successfully with NIMAS.

On the page number question, can you clarify how tagging should be done for unnumbered pages? The DAISY Structure Guidelines indicate that unnumbered pages should be indicated by providing the pagenum tags but without content. So our understanding of what you have below is that this tagging is acceptable:

Unnumbered pages (those that are not included in the pagination sequence) should be tagged but no page number should be included within the tag, allowing navigation by "next" and "previous" page controls.
http://www.daisy.org/z3986/structure/SG-DAISY3/part2-inline.html#pagenum
DAISY 3 Structure Guidelines - Part 2: Inline Elements<http://www.daisy.org/z3986/structure/SG-DAISY3/part2-inline.html#pagenum>
Part II(c): Inline Elements. DAISY 3 Structure Guidelines Last Revised: June 4, 2008. Inline elements are the structures that occur inside the block elements described in the previous chapter.
www.daisy.org



________________________________

**Comment by nicolegaines** [comment] 2022-10-11 13:18
Hi, Bert. The sentence in the guidelines directly after this indicates that if the unnumbered page is in sequence, then the tagging for the surrounding pages is used:
"Pages that are unnumbered but are a part of the page number sequence, should be marked with the correct page number in the sequence with the appropriate attribute, page="normal", page="front", or page="special"."
So the page attribute could include any of these values, depending on whether the unnumbered page is in sequence with the surrounding page numbers or not.

**Comment by bertfrees** [comment] 2022-10-11 13:25
> Pages that are unnumbered but are a part of the page number sequence, should be marked with the correct page number in the sequence

Exactly. So the content can not be empty in this case, right? It must contain the page number.

**Comment by bertfrees** [comment] 2022-10-11 13:30
Yes, at least this is my interpretation.

**Comment by nicolegaines** [comment] 2022-10-11 14:07
One more question: If you have five pages of endmatter that have no page numbers, should these be included in the pagination sequence, tagged as unnumbered? Is the only time something is considered "in sequence" when there is at least one additional numbered page afterward?

**Comment by nicolegaines** [comment] 2022-10-11 14:11
Sorry, my last comment was unclear. I meant to ask whether page numbers should be included in the tags for unnumbered pages at the end of the book (such as pages that include photo credits) when these are the last pages in the book and are not followed by any further numbered pages. (Or should they be tagged with empty pagenum tags and page="special"?) Thanks!

**Comment by bertfrees** [comment] 2022-10-11 16:31
Oh, that I don't know :-) I would think the choice is up to you in that case.

**Comment by nicolegaines** [comment] 2022-10-11 16:40
Thanks, Bert! Since I have you on the line, so to speak, can I ask whether it is okay to include color attributes in DAISY/NIMAS? I am not sure I have seen this in the Guidelines. I don't think it hurts anything--and it might be helpful in creating some accessible formats. Does this cause a problem for the Pipeline?

<li><p><span class="circle"><span class="background-color:#000000"><span class="color:#ffffff">3</span></span></span> <strong>Wie findest du das? Kreuz an und schreib Sätze in dein Heft. <img src="./images/thruout/common.jpg" alt="" /> <span class="color:#818285">4</span></strong></p>

________________________________

**Comment by bertfrees** [comment] 2022-10-11 17:14
I must say it is a funny use of the `class` attribute, but yes I believe it is okay. And if it does cause a problem for Pipeline, it should be fixable.

**Comment by bertfrees** [comment] 2024-01-16 21:29
> Regarding the DTBook to ODT conversion:
>
> The "Some content cannot be rendered here" warnings have nothing to do with using a NIMAS as input, I think. These are just shortcomings of the script.
> 
> The .odt file that you emailed can be opened just fine in LibreOffice. It could however be that the document has some issues that LibreOffice can cope with, but MS Word not. I ran the file through a ODF validator and it identified some issues. It could in theory also be that Word does not fully/correctly support ODF. Note that the script was primarily tested with OpenOffice/LibreOffice, much less with MS Word.

Actually this is a known issue. I forgot about it, but I found this warning in the code:

> WARNING! This converter doesn't produce valid OpenDocument Text as such. It relies on LibreOffice to do some fixing. Opening the ODT file in MS Word directly might fail.

The workaround is to first open the file in LibreOffice, then "Save a Copy", and after that you can successfully open the file in MS Word. @nicolegaines Can you let me know if this works for you. If you're interested I can look into performing the LibreOffice step automatically as part of the conversion.

**Comment by nicolegaines** [comment] 2024-01-16 21:35
Hi, Bert. The file that I sent wasn't an ODT, though. It was an RTF. Did it come over to you as an ODT? Or are you saying that Open Office opens the RTF and then converts it to ODT? Sorry for my confusion—I am not very familiar with Open Office. Thanks!

________________________________

**Comment by bertfrees** [comment] 2024-01-17 10:01
No, this is about the ODT issue you reported (see first comment of this issue):

> ODT test generated a file but Word could not open the file. Command line output and the Word error were sent to the daisy email address. It indicated that much of the file could not be rendered. Once the file was "recovered" it could not be opened.

We also corresponded over email about this issue, see the email named "Pipeline 2 unable to convert NIMAS to odt".

A note about RTF vs ODT: I think our ODT conversion is in a better state than the RTF one. DTBook to RTF is a legacy script that comes from Pipeline 1 and that I haven't ever worked on myself until now. When I was working on lists I immediately noticed another issue, but I lack the know-how for fixing it. I also don't know how to fix the images issue. The ODT conversion on the other hand is more recent and I've developed it myself, and the ODT format is better documented and better supported (more consistency across different tools).

**Comment by nicolegaines** [comment] 2024-01-18 14:08
Thanks, Bert. Sorry for the confusion—we had done this initial testing so long ago I had forgotten we tried the scripts for PEF and ODT just to see what would happen. Those aren't formats that we have seen used in the US.
Just to make sure I'm understanding, are you indicating that the 2023 Pipeline version includes fixes for the ODT conversion and it would be better to test that script again and see if we an get the files to open in Word?

________________________________

**Comment by bertfrees** [comment] 2024-01-18 22:25
No, the ODT conversion hasn't been improved for some time either. But what I'm saying is that the produced ODT file is not really intended to be opened by MS Word (directly). However when you open the file in LibreOffice (or OpenOffice.org) and then save a copy, the ODT file will have been fixed, so that you can subsequently open it (the copy) in MS Word.

**Comment by bertfrees** [comment] 2024-01-18 22:59
I'm going to close this issue now, since everything in it has either been addressed, or is covered by a more specific Github issue.

**Closed by bertfrees** 2024-01-18 22:59 UTC
Labels: ocul
