### ISSUE TITLE
There is no explicit log link in the XML returned by the Pipeline WS for a job that ended in error

### ISSUE THREAD

**Issue by marisademeglio** [daisy/pipeline#663] opened 2023-03-06 20:58 UTC
There is no explicit log link in the XML returned by the Pipeline WS for a job that ended in error:

```
<job href="http://127.0.0.1:49152/ws/jobs/aae0fc81-a553-4a43-a079-e0ae76a0e99c" id="aae0fc81-a553-4a43-a079-e0ae76a0e99c" status="ERROR">
<nicename>EPUB 3 Validator</nicename>
<script href="http://127.0.0.1:49152/ws/scripts/epub3-validator" id="epub3-validator" input-filesets="epub3">
<nicename>EPUB 3 Validator</nicename>
<description>Validates a EPUB.</description>
<version>2.0.3</version>
</script>
<messages progress="1.0">
<message content="Running EPUBCheck" level="INFO" portion="0.8" progress="1.0" sequence="18" timeStamp="1678127402171">
<message content="Failed to load content types: /Users/marisa/dev/pipeline-ui/node_modules/.dev-temp-build/resources/daisy-pipeline/jre/lib/content-types.properties" level="WARNING" sequence="25" timeStamp="1678127402183"/>
</message>
<message content="null (Please see detailed log for more info.)" level="ERROR" portion="1.0" progress="1.0" sequence="50" timeStamp="1678127402407"/>
</messages>
</job>
```

I could however infer it from the job url + "/log". It's a little hacky though.

_Originally posted by @marisademeglio in https://github.com/daisy/pipeline-ui/issues/94#issuecomment-1456731770_

**Comment by bertfrees** [comment] 2023-03-07 17:36
Thanks. Rings a bell. I think you might have told me before.

**Comment by bertfrees** [comment] 2023-03-07 19:44
Duplicate of https://github.com/daisy/pipeline-framework/issues/183.

**Comment by bertfrees** [comment] 2023-06-13 20:16
Fixed by https://github.com/daisy/pipeline-framework/commit/d6e2dcbe69fc60cc280f823312df667709f3c091.

**Closed by bertfrees** 2023-06-13 20:16 UTC
